# Generated by Django 4.2.3 on 2023-07-14 17:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(max_length=500)),
                ('post_image', models.ImageField(default='Spark.jpg', upload_to='upload_images/')),
                ('content', tinymce.models.HTMLField()),
                ('slug', models.SlugField(max_length=130, unique=True)),
                ('timeStamp', models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 14, 23, 11, 59, 591478))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
