# Generated by Django 4.2.3 on 2023-07-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_post_image_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.CharField(default='just now', max_length=20),
        ),
    ]
