# Generated by Django 4.2.3 on 2023-07-15 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 13, 17, 33, 661308)),
        ),
    ]
