# Generated by Django 4.2.3 on 2023-07-15 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_post_time_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.CharField(default=datetime.datetime(2023, 7, 15, 15, 58, 51, 850756), max_length=20),
        ),
    ]
