# Generated by Django 4.2.3 on 2023-07-15 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 16, 17, 38, 576840)),
        ),
    ]
