# Generated by Django 4.2.3 on 2023-07-19 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_timestamp_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='timeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 19, 18, 11, 44, 703426)),
        ),
    ]
